import { setTableData } from '.';
import { TableState } from '../../../components/Table/typings';
import { invoceListService } from '../../service/invoceList/invoceList';
import {AppThunkResult} from '../../store/index';
import { InvoceTableType } from '../../types/InvoceList/invoceListTypes';
import { hideLoading, showErrorModal, showLoading } from '../SettingStore';

export function getTableData(params: TableState['params']): AppThunkResult {
return async (dispatch) => {
    try {
        console.log(params)
    // const data = await userService.findByText(text);
    const data: InvoceTableType[] = [
        {
        numberOfParty: 4,
        countOfPriceTag: '2123',
        countOfLabels: '',
        nameOfItem: '',
        arivalName: '',
        markingStatus: '',
        TSOGroup: '',
        markingCategory: '',
        VATRate: '',
        quantityPack: '',
        numberParts: '',
        priceWithoutVAT: '',
        priceWithVAT: '',
        wholesalePriceWithoutVAT: '',
        wholesalePriceWithVAT: '',
        amountWholesaleWithoutVAT: '',
        amountVATWholesale: '',
        wholesaleAmountWithVATRetail: '',
        marginRublesPriceWithoutVAT: '',
        maxWholesalePriceRetailWithVAT: '',
        maxRetailPrice: '',
        retailAmountWithVAT: '',
        priceRegistryInvoice: '',
        expirationDate: '',
        series: '',
        manufacturerBarcode: '',
        currentBalance: '',
        lastRetailPriceWithVAT: '',
        GTDnumber: '',
        certificate: '',
        dateCertificate: '',
        laboratoryNumber: '',
        priceRegistryReference: '',
        ZHNVLS: '',
        batchNumber: '',
        internalBarcode: '',
        pharmaceuticalGroup: '',
        storageLocation: '',
        percentageWholesaleMargin: '',
        priceRetailWithoutVAT: '',
        maxNational: '',
        excise: '',
        dutyMargin: '',
        lot: '',
        productCode: '',
        priceRetailWithDiscount: '',
        reasonClaim: '',
        markingFeature: '',
        dateSaleManufacturer: '',
        comment: '',
        dataRosnPriceWithVAT: '',
        dataRosnPriceWithoutVAT: '',
        dataMaxRetailPrice: '',
        dataMarginWholesalePriceWithVAT: '',
        dataMarginManufacturerPriceWithoutVAT: '',
        dataCOCGroupWarehouseMargin: '',
        originalPriceWithVAT: '',
        INN: '',
        factoryPackaging: '',
        productGroupCode: '',
        nameProductGroup: '',
        numberUnitChanges: '',
        numberShelvingCards: '',
        nameSupplierProduct: '',
        nameManufactureSupplier: ''
      },
        {
        numberOfParty: 5,
        countOfPriceTag: 'fds',
        countOfLabels: 'fds',
        nameOfItem: '',
        arivalName: '',
        markingStatus: '',
        TSOGroup: '',
        markingCategory: '',
        VATRate: '',
        quantityPack: '',
        numberParts: '',
        priceWithoutVAT: '',
        priceWithVAT: '',
        wholesalePriceWithoutVAT: '',
        wholesalePriceWithVAT: '',
        amountWholesaleWithoutVAT: '',
        amountVATWholesale: '',
        wholesaleAmountWithVATRetail: '',
        marginRublesPriceWithoutVAT: '',
        maxWholesalePriceRetailWithVAT: '',
        maxRetailPrice: '',
        retailAmountWithVAT: '',
        priceRegistryInvoice: '',
        expirationDate: '',
        series: '',
        manufacturerBarcode: '',
        currentBalance: '',
        lastRetailPriceWithVAT: '',
        GTDnumber: '',
        certificate: '',
        dateCertificate: '',
        laboratoryNumber: '',
        priceRegistryReference: '',
        ZHNVLS: '',
        batchNumber: '',
        internalBarcode: '',
        pharmaceuticalGroup: '',
        storageLocation: '',
        percentageWholesaleMargin: '',
        priceRetailWithoutVAT: '',
        maxNational: '',
        excise: '',
        dutyMargin: '',
        lot: '',
        productCode: '',
        priceRetailWithDiscount: '',
        reasonClaim: '',
        markingFeature: '',
        dateSaleManufacturer: '',
        comment: '',
        dataRosnPriceWithVAT: '',
        dataRosnPriceWithoutVAT: '',
        dataMaxRetailPrice: '',
        dataMarginWholesalePriceWithVAT: '',
        dataMarginManufacturerPriceWithoutVAT: '',
        dataCOCGroupWarehouseMargin: '',
        originalPriceWithVAT: '',
        INN: '',
        factoryPackaging: '',
        productGroupCode: '',
        nameProductGroup: '',
        numberUnitChanges: '',
        numberShelvingCards: '',
        nameSupplierProduct: '',
        nameManufactureSupplier: ''
      }
    ]
      dispatch(setTableData(data))
    } catch (error) {
    console.log(error)
    }
};
}
export function getZapr(): AppThunkResult {
return async (dispatch) => {
    try {
      dispatch(showLoading())
      const data = await invoceListService.getTable()
      console.log(data)
    } catch (error) {
      let erMessage = 'Ошибка';
      if (error instanceof Error) {
        erMessage = error.message
      }
      dispatch(showErrorModal({isOpen: true, errorMessage: {errorMessage: erMessage, code: 123}}))
    }finally {
      dispatch(hideLoading());
    }
};
}

export function getTestUrl(): AppThunkResult {
  return async (dispatch) => {
      try {
        dispatch(showLoading())
        // const data = await invoceListService.getTest()
        // console.log(data)
      } catch (error) {
        let erMessage = 'Ошибка';
        if (error instanceof Error) {
          erMessage = error.message + error.name + error?.stack + error?.cause

        }
        dispatch(showErrorModal({isOpen: true, errorMessage: {errorMessage: erMessage, code: 0}}))
      }finally {
        dispatch(hideLoading());
      }
  };
}
export function getInvoceData(params: TableState['params']): AppThunkResult {
  return async (dispatch) => {
      try {
        dispatch(showLoading())
        
        console.log(params)
        const data: InvoceTableType[] = [
          {
          numberOfParty: 145,
          countOfPriceTag: '0',
          countOfLabels: '100',
          nameOfItem: 'Бетасерк таб. 8мг №30',
          arivalName: 'Верофарм/Россия',
          markingStatus: 'В ожидании',
          TSOGroup: 'ЖНВЛП от 100.00 до 500.00',
          markingCategory: 'Нет категории',
          VATRate: '10',
          quantityPack: '100',
          numberParts: '341,35',
          priceWithoutVAT: '',
          priceWithVAT: '',
          wholesalePriceWithoutVAT: '',
          wholesalePriceWithVAT: '',
          amountWholesaleWithoutVAT: '',
          amountVATWholesale: '',
          wholesaleAmountWithVATRetail: '',
          marginRublesPriceWithoutVAT: '',
          maxWholesalePriceRetailWithVAT: '',
          maxRetailPrice: '',
          retailAmountWithVAT: '',
          priceRegistryInvoice: '',
          expirationDate: '',
          series: '',
          manufacturerBarcode: '',
          currentBalance: '',
          lastRetailPriceWithVAT: '',
          GTDnumber: '',
          certificate: '',
          dateCertificate: '',
          laboratoryNumber: '',
          priceRegistryReference: '',
          ZHNVLS: '',
          batchNumber: '',
          internalBarcode: '',
          pharmaceuticalGroup: '',
          storageLocation: '',
          percentageWholesaleMargin: '',
          priceRetailWithoutVAT: '',
          maxNational: '',
          excise: '',
          dutyMargin: '',
          lot: '',
          productCode: '',
          priceRetailWithDiscount: '',
          reasonClaim: '',
          markingFeature: '',
          dateSaleManufacturer: '',
          comment: '',
          dataRosnPriceWithVAT: '',
          dataRosnPriceWithoutVAT: '',
          dataMaxRetailPrice: '',
          dataMarginWholesalePriceWithVAT: '',
          dataMarginManufacturerPriceWithoutVAT: '',
          dataCOCGroupWarehouseMargin: '',
          originalPriceWithVAT: '',
          INN: '',
          factoryPackaging: '',
          productGroupCode: '',
          nameProductGroup: '',
          numberUnitChanges: '',
          numberShelvingCards: '',
          nameSupplierProduct: '',
          nameManufactureSupplier: ''
        },
          {
          numberOfParty: 3,
          countOfPriceTag: '2',
          countOfLabels: '100',
          nameOfItem: 'ДуоРесп Спиромакс ингал.(пор. д/ингал. дозир.) 320мкг + 9мкг/доза 60 доз №1',
          arivalName: 'Norton(Waterford) выс. под торг.наим. IVAX/Ирландия',
          markingStatus: 'В ожидании',
          TSOGroup: 'ЖНВЛП от 100.00 до 500.00',
          markingCategory: 'Нет категории',
          VATRate: '10',
          quantityPack: '100',
          numberParts: '341,35',
          priceWithoutVAT: '',
          priceWithVAT: '',
          wholesalePriceWithoutVAT: '',
          wholesalePriceWithVAT: '',
          amountWholesaleWithoutVAT: '',
          amountVATWholesale: '',
          wholesaleAmountWithVATRetail: '',
          marginRublesPriceWithoutVAT: '',
          maxWholesalePriceRetailWithVAT: '',
          maxRetailPrice: '',
          retailAmountWithVAT: '',
          priceRegistryInvoice: '',
          expirationDate: '',
          series: '',
          manufacturerBarcode: '',
          currentBalance: '',
          lastRetailPriceWithVAT: '',
          GTDnumber: '',
          certificate: '',
          dateCertificate: '',
          laboratoryNumber: '',
          priceRegistryReference: '',
          ZHNVLS: '',
          batchNumber: '',
          internalBarcode: '',
          pharmaceuticalGroup: '',
          storageLocation: '',
          percentageWholesaleMargin: '',
          priceRetailWithoutVAT: '',
          maxNational: '',
          excise: '',
          dutyMargin: '',
          lot: '',
          productCode: '',
          priceRetailWithDiscount: '',
          reasonClaim: '',
          markingFeature: '',
          dateSaleManufacturer: '',
          comment: '',
          dataRosnPriceWithVAT: '',
          dataRosnPriceWithoutVAT: '',
          dataMaxRetailPrice: '',
          dataMarginWholesalePriceWithVAT: '',
          dataMarginManufacturerPriceWithoutVAT: '',
          dataCOCGroupWarehouseMargin: '',
          originalPriceWithVAT: '',
          INN: '',
          factoryPackaging: '',
          productGroupCode: '',
          nameProductGroup: '',
          numberUnitChanges: '',
          numberShelvingCards: '',
          nameSupplierProduct: '',
          nameManufactureSupplier: ''
        },
          {
            numberOfParty: 4,
            countOfPriceTag: '2',
            countOfLabels: '100',
            nameOfItem: 'Корвалол таб. №50',
            arivalName: 'Усолье-Сибирский ХФЗ/Россия',
            markingStatus: 'В ожидании',
            TSOGroup: 'НДС 10%',
            markingCategory: 'Нет категории',
            VATRate: '10',
            quantityPack: '100',
            numberParts: '83,53',
          priceWithoutVAT: '',
          priceWithVAT: '',
          wholesalePriceWithoutVAT: '',
          wholesalePriceWithVAT: '',
          amountWholesaleWithoutVAT: '',
          amountVATWholesale: '',
          wholesaleAmountWithVATRetail: '',
          marginRublesPriceWithoutVAT: '',
          maxWholesalePriceRetailWithVAT: '',
          maxRetailPrice: '',
          retailAmountWithVAT: '',
          priceRegistryInvoice: '',
          expirationDate: '',
          series: '',
          manufacturerBarcode: '',
          currentBalance: '',
          lastRetailPriceWithVAT: '',
          GTDnumber: '',
          certificate: '',
          dateCertificate: '',
          laboratoryNumber: '',
          priceRegistryReference: '',
          ZHNVLS: '',
          batchNumber: '',
          internalBarcode: '',
          pharmaceuticalGroup: '',
          storageLocation: '',
          percentageWholesaleMargin: '',
          priceRetailWithoutVAT: '',
          maxNational: '',
          excise: '',
          dutyMargin: '',
          lot: '',
          productCode: '',
          priceRetailWithDiscount: '',
          reasonClaim: '',
          markingFeature: '',
          dateSaleManufacturer: '',
          comment: '',
          dataRosnPriceWithVAT: '',
          dataRosnPriceWithoutVAT: '',
          dataMaxRetailPrice: '',
          dataMarginWholesalePriceWithVAT: '',
          dataMarginManufacturerPriceWithoutVAT: '',
          dataCOCGroupWarehouseMargin: '',
          originalPriceWithVAT: '',
          INN: '',
          factoryPackaging: '',
          productGroupCode: '',
          nameProductGroup: '',
          numberUnitChanges: '',
          numberShelvingCards: '',
          nameSupplierProduct: '',
          nameManufactureSupplier: ''
        },
          {
            numberOfParty: 5,
            countOfPriceTag: '2',
            countOfLabels: '100',
            nameOfItem: 'Снуп фл.(спрей наз. дозир.) 0,1% (90мкг/доза 150доз) 15мл №1',
            arivalName: 'Hemomont/Черногория',
            markingStatus: 'В ожидании',
            TSOGroup: 'ЖНВЛП до 100.00',
            markingCategory: 'Нет категории',
            VATRate: '10',
            quantityPack: '100',
            numberParts: '207,66',
          priceWithoutVAT: '',
          priceWithVAT: '',
          wholesalePriceWithoutVAT: '',
          wholesalePriceWithVAT: '',
          amountWholesaleWithoutVAT: '',
          amountVATWholesale: '',
          wholesaleAmountWithVATRetail: '',
          marginRublesPriceWithoutVAT: '',
          maxWholesalePriceRetailWithVAT: '',
          maxRetailPrice: '',
          retailAmountWithVAT: '',
          priceRegistryInvoice: '',
          expirationDate: '',
          series: '',
          manufacturerBarcode: '',
          currentBalance: '',
          lastRetailPriceWithVAT: '',
          GTDnumber: '',
          certificate: '',
          dateCertificate: '',
          laboratoryNumber: '',
          priceRegistryReference: '',
          ZHNVLS: '',
          batchNumber: '',
          internalBarcode: '',
          pharmaceuticalGroup: '',
          storageLocation: '',
          percentageWholesaleMargin: '',
          priceRetailWithoutVAT: '',
          maxNational: '',
          excise: '',
          dutyMargin: '',
          lot: '',
          productCode: '',
          priceRetailWithDiscount: '',
          reasonClaim: '',
          markingFeature: '',
          dateSaleManufacturer: '',
          comment: '',
          dataRosnPriceWithVAT: '',
          dataRosnPriceWithoutVAT: '',
          dataMaxRetailPrice: '',
          dataMarginWholesalePriceWithVAT: '',
          dataMarginManufacturerPriceWithoutVAT: '',
          dataCOCGroupWarehouseMargin: '',
          originalPriceWithVAT: '',
          INN: '',
          factoryPackaging: '',
          productGroupCode: '',
          nameProductGroup: '',
          numberUnitChanges: '',
          numberShelvingCards: '',
          nameSupplierProduct: '',
          nameManufactureSupplier: ''
        },
      ]
        // const data = await invoceListService.getInvoceData(params)
        dispatch(setTableData(data))
      } catch (error) {
        let erMessage = 'Ошибка';
        if (error instanceof Error) {
          erMessage = error.message + error.name + error?.stack + error?.cause

        }
        dispatch(showErrorModal({isOpen: true, errorMessage: {errorMessage: erMessage, code: 0}}))
      }finally {
        dispatch(hideLoading());
      }
  };
}