import { setTableData } from '.';
import { TableState } from '../../../components/Table/typings';
import {AppThunkResult} from '../../store/index';
import { InvoceTableType } from '../../types/InvoceList/invoceListTypes';

export function getTableData(params: TableState['params']): AppThunkResult {
return async (dispatch) => {
    try {
        console.log(params)
    // const data = await userService.findByText(text);
    const data: InvoceTableType[] = [
        {
        numberOfParty: 1,
        countOfPriceTag: '2123',
        countOfLabels: '',
        nameOfItem: '',
        arivalName: '',
        markingStatus: '',
        TSOGroup: '',
        markingCategory: '',
        VATRate: '',
        quantityPack: '',
        numberParts: '',
        priceWithoutVAT: '',
        priceWithVAT: '',
        wholesalePriceWithoutVAT: '',
        wholesalePriceWithVAT: '',
        amountWholesaleWithoutVAT: '',
        amountVATWholesale: '',
        wholesaleAmountWithVATRetail: '',
        marginRublesPriceWithoutVAT: '',
        maxWholesalePriceRetailWithVAT: '',
        maxRetailPrice: '',
        retailAmountWithVAT: '',
        priceRegistryInvoice: '',
        expirationDate: '',
        series: '',
        manufacturerBarcode: '',
        currentBalance: '',
        lastRetailPriceWithVAT: '',
        GTDnumber: '',
        certificate: '',
        dateCertificate: '',
        laboratoryNumber: '',
        priceRegistryReference: '',
        ZHNVLS: '',
        batchNumber: '',
        internalBarcode: '',
        pharmaceuticalGroup: '',
        storageLocation: '',
        percentageWholesaleMargin: '',
        priceRetailWithoutVAT: '',
        maxNational: '',
        excise: '',
        dutyMargin: '',
        lot: '',
        productCode: '',
        priceRetailWithDiscount: '',
        reasonClaim: '',
        markingFeature: '',
        dateSaleManufacturer: '',
        comment: '',
        dataRosnPriceWithVAT: '',
        dataRosnPriceWithoutVAT: '',
        dataMaxRetailPrice: '',
        dataMarginWholesalePriceWithVAT: '',
        dataMarginManufacturerPriceWithoutVAT: '',
        dataCOCGroupWarehouseMargin: '',
        originalPriceWithVAT: '',
        INN: '',
        factoryPackaging: '',
        productGroupCode: '',
        nameProductGroup: '',
        numberUnitChanges: '',
        numberShelvingCards: '',
        nameSupplierProduct: '',
        nameManufactureSupplier: ''
      },
        {
        numberOfParty: 5,
        countOfPriceTag: 'fds',
        countOfLabels: 'fds',
        nameOfItem: '',
        arivalName: '',
        markingStatus: '',
        TSOGroup: '',
        markingCategory: '',
        VATRate: '',
        quantityPack: '',
        numberParts: '',
        priceWithoutVAT: '',
        priceWithVAT: '',
        wholesalePriceWithoutVAT: '',
        wholesalePriceWithVAT: '',
        amountWholesaleWithoutVAT: '',
        amountVATWholesale: '',
        wholesaleAmountWithVATRetail: '',
        marginRublesPriceWithoutVAT: '',
        maxWholesalePriceRetailWithVAT: '',
        maxRetailPrice: '',
        retailAmountWithVAT: '',
        priceRegistryInvoice: '',
        expirationDate: '',
        series: '',
        manufacturerBarcode: '',
        currentBalance: '',
        lastRetailPriceWithVAT: '',
        GTDnumber: '',
        certificate: '',
        dateCertificate: '',
        laboratoryNumber: '',
        priceRegistryReference: '',
        ZHNVLS: '',
        batchNumber: '',
        internalBarcode: '',
        pharmaceuticalGroup: '',
        storageLocation: '',
        percentageWholesaleMargin: '',
        priceRetailWithoutVAT: '',
        maxNational: '',
        excise: '',
        dutyMargin: '',
        lot: '',
        productCode: '',
        priceRetailWithDiscount: '',
        reasonClaim: '',
        markingFeature: '',
        dateSaleManufacturer: '',
        comment: '',
        dataRosnPriceWithVAT: '',
        dataRosnPriceWithoutVAT: '',
        dataMaxRetailPrice: '',
        dataMarginWholesalePriceWithVAT: '',
        dataMarginManufacturerPriceWithoutVAT: '',
        dataCOCGroupWarehouseMargin: '',
        originalPriceWithVAT: '',
        INN: '',
        factoryPackaging: '',
        productGroupCode: '',
        nameProductGroup: '',
        numberUnitChanges: '',
        numberShelvingCards: '',
        nameSupplierProduct: '',
        nameManufactureSupplier: ''
      }
    ]
      dispatch(setTableData(data))
    } catch (error) {
    console.log(error)
    }
};
}